[package]
name = "conways_game_of_life_dyn_lib"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]

[dev-dependencies]
inline_colorization = "0.1.6"
